from fastapi import FastAPI, BackgroundTasks
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import uvicorn
import uuid
import os
import json
import time

app = FastAPI(title="Gods Eye AI Reconstruction Engine")

# Allow frontend to access this backend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

class ReconstructionRequest(BaseModel):
    min_lat: float
    max_lat: float
    min_lon: float
    max_lon: float
    resolution: float = 0.5

# In-memory store for task progress
tasks = {}

def run_reconstruction_pipeline(task_id: str, req: ReconstructionRequest):
    """
    This is the core pipeline that simulates the execution of VoxCity/Sat-Skylines.
    1. Fetch satellite imagery / footprints (simulated)
    2. Run PyTorch model to infer building height and generate mesh (simulated)
    3. Generate 3D Tileset using py3dtiles (simulated output generation)
    """
    tasks[task_id] = {"status": "processing", "progress": 0, "message": "Fetching satellite imagery..."}
    time.sleep(2)
    
    tasks[task_id] = {"status": "processing", "progress": 30, "message": "Extracting footprints (OSM/Overture proxy)..."}
    time.sleep(2)
    
    tasks[task_id] = {"status": "processing", "progress": 50, "message": "Running PyTorch 3D extrusion model (Sat-Skylines placeholder)..."}
    time.sleep(3)
    
    tasks[task_id] = {"status": "processing", "progress": 80, "message": "Converting GLTF meshes to 3D Tiles format..."}
    
    # In a real implementation, we would output `.b3dm` files into a static directory.
    # We will scaffold a dummy directory here.
    output_dir = os.path.join(os.path.dirname(__file__), "static", "tiles", task_id)
    os.makedirs(output_dir, exist_ok=True)
    
    with open(os.path.join(output_dir, "tileset.json"), "w") as f:
        # A minimal mock tileset.json for Cesium
        json.dump({
            "asset": { "version": "1.1" },
            "geometricError": 100,
            "root": {
                "boundingVolume": {
                    "region": [
                        req.min_lon, req.min_lat, req.max_lon, req.max_lat, 0, 100
                    ]
                },
                "geometricError": 0,
                "refine": "ADD",
                "content": {
                    "uri": "mock_data.b3dm"
                }
            }
        }, f)
        
    time.sleep(2)
    
    tasks[task_id] = {
        "status": "complete", 
        "progress": 100, 
        "message": "Reconstruction successful.",
        "tileset_url": f"http://localhost:8000/static/tiles/{task_id}/tileset.json"
    }


@app.post("/api/reconstruct")
async def start_reconstruction(req: ReconstructionRequest, background_tasks: BackgroundTasks):
    task_id = str(uuid.uuid4())
    tasks[task_id] = {"status": "queued", "progress": 0, "message": "Task queued..."}
    
    background_tasks.add_task(run_reconstruction_pipeline, task_id, req)
    
    return {"task_id": task_id}

@app.get("/api/status/{task_id}")
async def get_status(task_id: str):
    return tasks.get(task_id, {"status": "not_found", "message": "Task ID not found."})

# Serve the static 3D tiles generated by the engine
from fastapi.staticfiles import StaticFiles
os.makedirs(os.path.join(os.path.dirname(__file__), "static"), exist_ok=True)
app.mount("/static", StaticFiles(directory=os.path.join(os.path.dirname(__file__), "static")), name="static")

if __name__ == "__main__":
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
